language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "dev"
  - "blead"

matrix:
  include:
    - perl: "5.24-thr"
      env: COVERAGE=coveralls
    - perl: "5.20-thr"
      env: COVERAGE=codecov
  allow_failures:
    - perl: blead

sudo: false

addons:
  apt:
    packages:
    - libgirepository1.0-dev
    - libgtk3-perl
    - xvfb
    - xauth
    - libdbus-1-dev
    - dunst

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - ln -vs bin lib

install:
  - cpan-install --deps
  - cpan-install --coverage
  - rm -vf t/author-critic.t

script:
  - xvfb-run env NO_AT_BRIDGE=1 prove -l -j$(test-jobs) $(test-files)

notifications:
  irc: "irc.lugs.ch#kivamon"
